# Generated by Django 4.2.21 on 2025-05-16 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("follows", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="following",
            new_name="followed",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followed")},
        ),
    ]
